name: "Podcast Generator"
author: "At now Gerzsony"
description: "Generates feed for a podcast from YAML file"
runs:
  using: "docker"
  image: "Dockerfile"
branding:
  icon: "git-branch"
  color: "red"
inputs:
  email:
    description: The comitters email address
    required: true
    default: ${{ github.actor }}@localhost
  name:
    description: The comitters name
    required: true
    default: ${{ github.actor }}   